# Generated by Django 5.0.3 on 2024-03-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=50)),
                ('supplier', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
