# Generated by Django 5.0.3 on 2024-03-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dobaMainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_name',
        ),
    ]
