# Generated by Django 5.0.3 on 2024-04-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobaMainApp', '0003_document_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_content',
            field=models.BinaryField(default=b''),
        ),
    ]
