# Generated by Django 5.0.3 on 2024-04-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobaMainApp', '0004_document_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='sampleDB/'),
        ),
        migrations.AddField(
            model_name='document',
            name='orig_docName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
