# Generated by Django 5.0.3 on 2024-04-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobaMainApp', '0005_document_file_path_document_orig_docname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(default='', max_length=512),
        ),
    ]
