# Generated by Django 5.0.6 on 2024-08-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobaMainApp', '0006_alter_document_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='po_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], default='', max_length=15),
        ),
    ]
