# Generated by Django 5.0.3 on 2024-09-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobaMainApp', '0007_document_po_number_document_remarks_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default='', max_length=15),
        ),
    ]
